### ISSUE TITLE
BB  2.2.0.36

### ISSUE THREAD

**Issue by grnstv** [Pitmairen/bryton-offline#3]
Hey! Can you upload brytonbridge 2.2.0.36 to google docs? 
It's definetly not working with 2.8.0.14

**Comment by Pitmairen** [comment]
I have uploaded brytonbridge 2.2.0.36. But i haven't tested this application i a long time so i don't know if it works anymore.

**Comment by grnstv** [comment]
No, it doesn't unfortunately.
